# Generated by Django 3.1.3 on 2020-12-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.CharField(blank=True, choices=[('недвижимость', 'недвижимость'), ('авто', 'авто'), ('сельхоз', 'сельхоз'), ('покупка/продажа', 'покупка/продажа'), ('работа', 'работа'), ('услуги', 'услуги'), ('электроника', 'электроника'), ('попутчик', 'попутчик'), ('потеряли', 'потеряли'), ('нашли', 'нашли')], max_length=250, verbose_name='Категории'),
        ),
    ]
