# Generated by Django 3.1.3 on 2020-12-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20201202_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(blank=True, choices=[('сом', 'сом'), ('доллар', 'доллар'), ('евро', 'евро'), ('лира', 'лира'), ('рубль', 'рубль')], max_length=250, verbose_name='цена в'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='whatsapp_phone',
            field=models.IntegerField(blank=True),
        ),
    ]
