# Generated by Django 3.1.3 on 2020-12-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20201216_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
