# Generated by Django 3.1.3 on 2020-12-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_auto_20201217_1737'),
        ('listings', '0002_auto_20201217_1756'),
    ]

    operations = [
    ]
