# Generated by Django 3.1.3 on 2020-12-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_merge_20201217_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.CharField(blank=True, choices=[('недвижимость', 'недвижимость'), ('авто', 'авто'), ('сельхоз', 'сельхоз'), ('покупка/продажа', 'покупка/продажа'), ('работа', 'работа'), ('услуги', 'услуги'), ('электроника', 'электроника'), ('попутчик', 'попутчик'), ('потеряли', 'потеряли'), ('нашли', 'нашли')], max_length=50, verbose_name='Категории'),
        ),
    ]
