# Generated by Django 3.1.3 on 2020-12-17 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('listings', '0011_auto_20201217_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listings', to='category.category', verbose_name='Категории'),
        ),
    ]
