# Generated by Django 3.1.3 on 2020-12-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categories',
        ),
    ]
